---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rester-dummy-run-enviroment-h2
data:
  ENABLE_ACTUACTORS: "true"
  DB_URL: jdbc:h2:file:/tmp/rester-dummy-run-db
  DB_DRIVER_CLASSNAME: org.h2.Driver
  DB_DIALECT: org.hibernate.dialect.H2Dialect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rester-dummy-run-enviroment-postgres
data:
  ENABLE_ACTUACTORS: "true"
  H2_CONSOLE: "false"
  DB_URL: jdbc:postgresql://postgres.db.local:5432/rester
  DB_DRIVER_CLASSNAME: org.postgresql.Driver
  DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: Secret
metadata:
  name: rester-dummy-run-secret-h2
type: Opaque
stringData:
  DB_USR: sa
#  DB_PWD:
---
apiVersion: v1
kind: Secret
metadata:
  name: rester-dummy-run-secret-postgres
type: Opaque
stringData:
  DB_USR: postgres
  DB_PWD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rester-dummy-run
spec:
  selector:
    matchLabels:
      app: rester-dummy-run
  template:
    metadata:
      labels:
        app: rester-dummy-run
    spec:
      containers:
        - name: rester-dummy-run
          image: scaamanho/resters-dummy-run
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: rester-dummy-run-enviroment-postgres
            - secretRef:
                name: rester-dummy-run-secret-postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rester-dummy-run
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: rester-dummy-run
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rester-dummy-run
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - rester.minikube.local
  rules:
    - host: rester.minikube.local
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: rester-dummy-run
                port:
                  number: 80
