DROP TABLE IF EXISTS REST_DUMMY;
CREATE TABLE REST_DUMMY (ID INT PRIMARY KEY, NAME VARCHAR(255), DESC VARCHAR(255), CONTENT VARCHAR(255));


DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST (ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');